version: "3.9"

services:
  db: 
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=laundry-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
